### ISSUE TITLE
Provide an example ?

### ISSUE THREAD

**Issue by unityweb** [rainforestapp/Docker-Terminal#1]
Hi, 
Can you please provide a 'howto' or 'example' on how we can use this ? 

Thanks in advance

**Comment by ukd1** [comment]
It's baked in to shipyard now, so you can check it out there. Also there is `index.html` in the root of the project. It needs the host changing, but that should be it! :+1:

**Comment by ukd1** [comment]
I've just renamed the `index.html` to `example.html`

**Comment by unityweb** [comment]
Thanks for your reply; I did all that already but when I enter the 'tty' it says 'session started' and then I see nothing, can't type anything. My goal was to have a 'shell' in that windows (like an ssh interactive shell). What should I run to get that ?
